language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
env:
  - CI=true
script: npm run build-storybook && npm run build-storybook

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  local_dir: storybook-static
  # keep_history: true
on:
  branch: test1
# $GITHUB_TOKEN：70fdd6934be9c43e432f480ffa49004ccfebdf95
